FROM ubuntu:14.04
RUN apt-get update -qq

# Install Ansible
RUN sed -i 's/101/0/' /usr/sbin/policy-rc.d
RUN apt-get install -y -qq software-properties-common git git curl
RUN apt-add-repository -y ppa:ansible/ansible
RUN apt-get update -qq
RUN apt-get install -y ansible wget -qq

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local devshop_install_profile=hostmaster" > /etc/ansible/hosts

RUN wget https://github.com/opendevshop/devshop/releases/download/1.0.0-beta10/install.sh && \
  bash install.sh --hostname=aegir.docker